### ISSUE TITLE
How to get charging LED working?

### ISSUE THREAD

**Issue by SchneHa** [amperpirat/MAX77650-Arduino-Library#2]
I'm playing around with MAX32620FTHR which includes a MAX22650 chip. I enabled charging and it seems to work, but the LED always remains dark. Isn't it indicating automatically if charging or not?
Can you make an example how to switch it to red during charging and to green if charging is done, please.

**Comment by amperpirat** [comment]
Hi SchneHa,
the build-in charger is independant from the LEDs. This was mainly done because every vendor of equipment has its own color-code. Saying this, if you want to change the PMIC-LED-color to reflect your charger state, you've to do this in the host code. There're examples to set the colors of the LEDs.
Have fun,
Ole

**Comment by amperpirat** [comment]
I'll try to provide an example in the next few days and add it to the examples.

**Comment by SchneHa** [comment]
Any news about the example of the charger LED?

**Comment by amperpirat** [comment]
I just uploaded the code. Please feel free to report any errors.
Please be aware that this code only handles charger related interrupts regarding CHG_DTLS.
LED colors:
green: charger done, charger off AND charger input valid (battery fully charged)
red: charging

**Comment by SchneHa** [comment]
Thank you for the example. I tried to merge into my code but I got the following error in the following line:
pinMode(MAX32620_INT, INPUT_PULLUP);

Error message:
maxim_ino:140: error: 'MAX32620_INT' was not declared in this scope
   pinMode(MAX32620_INT, INPUT_PULLUP);
           ^
